/*
Data exploration and profiling script for the DataWarehouse project. 
Performs basic queries, data quality checks, simple aggregations, rankings, 
and business metrics across gold schema dimensions (customers, products, dates) 
and fact_sales table.
*/

USE DataWarehouse;

-- 1. DATABASE EXPLORATION

-- Explore All Objects in the Database

SELECT *
FROM INFORMATION_SCHEMA.TABLES
;

-- Explore All Columns in the Database

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'
;

-- 2. DIMENSIONS EXPLORATION

-- Explore all Countries Customers come from

SELECT DISTINCT country
FROM gold.dim_customers
;

-- Explore all Product Categories "The Major Divisions"

SELECT DISTINCT category, subcategory, product_name
FROM gold.dim_products
ORDER BY 1,2,3
;

-- 3. DATE EXPLORATION 

-- The Date of the first and last Order

SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(month, MIN(order_date), MAX(order_date)) AS order_range_months
FROM gold.fact_sales
;

-- The youngest and oldest Customer

SELECT
	MIN(birthdate) AS oldest_customer,
	DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
	MAX(birthdate) AS youngest_customer,
	DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers
;

-- 4. MEASURES EXPLORATION

-- Total Sales

SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales
;

-- How many Items are Sold

SELECT SUM(quantity) AS total_quantity
FROM gold.fact_sales
;

-- Average Selling Price

SELECT AVG(price) AS avg_price
FROM gold.fact_sales
;

-- Total Number of Orders

SELECT COUNT(order_number) AS total_orders
FROM gold.fact_sales
;

--to exclude duplicates (DISTINCT)
SELECT COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales
;

-- Total Number of Products

SELECT COUNT(product_key) AS total_products
FROM gold.dim_products
;

SELECT COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products
;

-- Total Number of Customers

SELECT COUNT(customer_key) AS total_customers
FROM gold.dim_customers
;

-- Total Number of Customers that has Placed an Order

SELECT COUNT(DISTINCT customer_key) AS total_customers
FROM gold.fact_sales
;

-- REPORT: ALL KEY METRICS OF THE BUSINESS

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL 
SELECT 'Total Quantity', SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL 
SELECT 'Average Price', AVG(price) AS avg_price FROM gold.fact_sales
UNION ALL 
SELECT 'Total Nr. Orders', COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_key) AS total_products FROM gold.dim_products
UNION ALL 
SELECT 'Total Nr. Customers', COUNT(customer_key) AS total_customers FROM gold.dim_customers
;

-- MAGNITUDE ANALYSIS

-- Total Customers by Country

SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Total Customers by Gender

SELECT 
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Total Products by Category

SELECT 
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Average Cost in each Category

SELECT 
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- Total Revenue Generated for each Category

SELECT
	dp.category,
	SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp
ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;

-- Total Revenue Generated by each Customer

SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
	c.customer_key, 
	c.first_name, 
	c.last_name
ORDER BY total_revenue DESC;

-- Distribution of Sold Items Across Countries

SELECT
	c.country,
	SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;

-- RANKING (TOP N PERFORMERS - BOTTOM N PERFORMERS)

-- 5 Products that Generate the Highest Revenue

SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- 5 Worst-performing Products in Terms of Sales

SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;

-- Same result with the window function

SELECT *
FROM (
	SELECT 
		p.product_name,
		SUM(f.sales_amount) AS total_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON f.product_key = p.product_key
	GROUP BY p.product_name)t
WHERE rank_products <= 5
;

-- Top 10 Customers who have Generated the Highest Revenue

SELECT TOP 10
	c.customer_key,
	c.first_name, 
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
	c.customer_key,
	c.first_name, 
	c.last_name
ORDER BY total_revenue DESC;

-- 3 Customers with the Fewest Orders placed

SELECT TOP 3
	c.customer_key,
	c.first_name, 
	c.last_name,
	COUNT(DISTINCT f.order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
	c.customer_key,
	c.first_name, 
	c.last_name
ORDER BY total_orders;
